### ISSUE TITLE
Constraint explorer does not work

### ISSUE THREAD

**Issue by ardeujho** [doublec/aliceml-abandoned#4]
The explorer shows an empty window when [following the instructions to use the Explorer](http://www.ps.uni-saarland.de/alice/manual/tour.html#constraints) to view a constraint solution. To reproduce this you'll need to first do the workaround/fix in issue #1.

**Comment by doublec** [comment]
I confirm this doesn't work with a build from master. Building from the [original Alice source](http://www.ps.uni-saarland.de/alice/download/sources/) does work. We'll have to work out what has changed since then.

**Comment by doublec** [comment]
Following up at aliceml/aliceml#1.
