### ISSUE TITLE
Trailing space in console prevents command from being evaluated

### ISSUE THREAD

**Issue by ardeujho** [doublec/aliceml-abandoned#5]
Entering code without a trailing space after the semicolon works fine in the interactive console when pressing enter:

```
1+2;<enter>
val it : int = 2
```

Adding a trailing space followed by a newline causes the console to wait for further input. Only another semicolon appears to cause the first line to be processed:

```
1+2;<space><enter>
;
val it : int = 2
```

**Comment by doublec** [comment]
Following up at aliceml/aliceml#4.
